'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,Save,UserRound,MapPin,Mail,FileText,Plus,Trash2,CheckCircle2,RefreshCw} from 'lucide-react';

export default function Profile(){
 const [p,setP]=useState<any>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/profile',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load profile');setP({...d,skills:[...(d.skills||[])]})}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const set=(key:string,value:any)=>setP((x:any)=>({...x,[key]:value}));
 const save=async(e:any)=>{e.preventDefault();setSaving(true);setMessage('');setError('');try{const r=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save profile');setP({...d,skills:[...(d.skills||[])]});setMessage('Profile updated successfully.')}catch(e:any){setError(e.message)}finally{setSaving(false)}};
 if(loading)return <main className="mx-auto max-w-3xl px-5 py-20 text-center"><div className="animate-pulse text-zinc-500">Loading profile…</div></main>;
 if(error&&!p)return <main className="mx-auto max-w-2xl px-5 py-20 text-center"><div className="glass rounded-3xl p-8"><h1 className="text-2xl font-black">Profile unavailable</h1><p className="mt-2 text-sm text-zinc-500">{error}</p><button onClick={load} className="mt-5 rounded-xl bg-green-400 px-5 py-3 text-sm font-black text-black"><RefreshCw size={15} className="mr-2 inline"/>Retry</button></div></main>;
 return <main className="mx-auto max-w-5xl px-5 py-9 md:py-12"><Link href="/candidate" className="text-sm text-zinc-500 hover:text-white"><ArrowLeft size={15} className="mr-2 inline"/>Back to My Career</Link><div className="mt-5"><p className="text-xs font-bold uppercase tracking-[.2em] text-green-300">Professional profile</p><h1 className="mt-3 text-4xl font-black tracking-tight">Your profile, <span className="gradient-text">your story.</span></h1><p className="mt-3 max-w-2xl text-zinc-500">Keep your skills, location, headline and resume link ready for every application.</p></div>
  {message&&<div className="mt-6 rounded-2xl border border-green-400/20 bg-green-400/5 p-4 text-sm text-green-300"><CheckCircle2 size={16} className="mr-2 inline"/>{message}</div>}
  {error&&p&&<div className="mt-6 rounded-2xl border border-red-400/20 bg-red-400/5 p-4 text-sm text-red-300">{error}</div>}
  <form onSubmit={save} className="mt-7 grid gap-6 lg:grid-cols-[280px_1fr]">
   <aside className="glass h-fit rounded-3xl p-6"><div className="grid h-24 w-24 place-items-center rounded-3xl bg-green-400 text-3xl font-black text-black">{p.name.slice(0,2).toUpperCase()}</div><h2 className="mt-5 text-xl font-black">{p.name}</h2><p className="mt-1 text-sm text-green-300">Candidate profile</p><div className="mt-6 space-y-3 text-sm text-zinc-500"><div><MapPin size={15} className="mr-2 inline"/>{p.location||'Location not set'}</div><div className="break-all"><Mail size={15} className="mr-2 inline"/>{p.email}</div></div></aside>
   <section className="glass rounded-3xl p-6 md:p-8"><div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-medium">Full name<input className="field mt-2" value={p.name||''} onChange={e=>set('name',e.target.value)}/></label><label className="text-sm font-medium">Email<input disabled className="field mt-2 opacity-60" value={p.email||''}/><span className="mt-1 block text-xs text-zinc-600">Email is linked to the demo account.</span></label><label className="text-sm font-medium md:col-span-2">Professional headline<input className="field mt-2" value={p.headline||''} onChange={e=>set('headline',e.target.value)} placeholder="e.g. Software Developer · Python · Java · Web"/></label><label className="text-sm font-medium md:col-span-2">Location<input className="field mt-2" value={p.location||''} onChange={e=>set('location',e.target.value)} placeholder="Ahmedabad, India"/></label></div>
    <div className="mt-7"><div className="flex items-center justify-between"><div><h2 className="font-black">Skills</h2><p className="mt-1 text-xs text-zinc-600">Add the skills you want employers to match.</p></div><button type="button" onClick={()=>set('skills',[...(p.skills||[]),''])} className="rounded-lg border border-white/10 px-3 py-2 text-xs font-bold"><Plus size={14} className="mr-1 inline"/>Add skill</button></div><div className="mt-4 space-y-2">{(p.skills||[]).map((s:string,i:number)=><div className="flex gap-2" key={i}><input className="field" value={s} onChange={e=>{const a=[...p.skills];a[i]=e.target.value;set('skills',a)}} placeholder="e.g. Python"/><button type="button" onClick={()=>set('skills',p.skills.filter((_:any,j:number)=>j!==i))} className="rounded-xl border border-white/10 px-3 text-zinc-500 hover:text-red-300"><Trash2 size={16}/></button></div>)}</div></div>
    <div className="mt-7 rounded-2xl border border-white/[.07] bg-white/[.025] p-5"><div className="flex gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-green-400/10 text-green-300"><FileText size={18}/></div><div className="flex-1"><h2 className="font-black">Resume</h2><p className="mt-1 text-xs text-zinc-600">Paste a public resume URL for this demo portal.</p><input className="field mt-3" value={p.resumeUrl||''} onChange={e=>set('resumeUrl',e.target.value)} placeholder="https://drive.google.com/..."/></div></div></div>
    <div className="mt-7 flex flex-col-reverse justify-end gap-2 border-t border-white/10 pt-5 sm:flex-row"><Link href="/candidate" className="rounded-xl border border-white/10 px-5 py-3 text-center text-sm font-bold">Cancel</Link><button disabled={saving} className="rounded-xl bg-green-400 px-6 py-3 text-sm font-black text-black disabled:opacity-50"><Save size={15} className="mr-2 inline"/>{saving?'Saving…':'Save profile'}</button></div>
   </section>
  </form>
 </main>
}
