import fs from 'fs';
import path from 'path';

type User = { id:number; name:string; email:string; role:string; headline:string; location:string; skills:string[]; resumeUrl:string|null; avatarUrl?:string|null };
type Job = { id:number; title:string; company:string; location:string; workMode:string; employmentType:string; salaryMin:number|null; salaryMax:number|null; currency:string; description:string; requirements:string[]; benefits:string[]; skills:string[]; featured:boolean; status:string; recruiterId:number; createdAt:string; updatedAt:string; _count?:{applications:number} };
type Application = { id:number; jobId:number; candidateId:number; status:string; coverLetter:string; resumeUrl:string|null; matchScore:number; recruiterNote:string|null; appliedAt:string; updatedAt:string };

type Store = { users:User[]; jobs:Job[]; applications:Application[]; nextUserId:number; nextJobId:number; nextApplicationId:number };
const file=path.join(process.cwd(),'data','demo-store.json');
const now=()=>new Date().toISOString();
const seedJobs=[
['Software Engineer','Google','Bengaluru, India','HYBRID','FULL_TIME',1800000,3200000,['JavaScript','TypeScript','Python','DSA','React'],true,'Build reliable products used by millions of people. Work with product and engineering teams to ship high-quality software.',['Strong programming fundamentals','DSA and problem solving','Experience with web technologies'],['Health insurance','Learning budget','Flexible work']],
['Frontend Developer','Razorpay','Bengaluru, India','HYBRID','FULL_TIME',1000000,1800000,['React','Next.js','TypeScript','CSS'],true,'Create fast, accessible and polished financial product experiences.',['React and TypeScript','Strong CSS fundamentals','API integration experience'],['ESOP','Flexible hours','Wellness support']],
['Python Developer Intern','TechNova Labs','Remote - India','REMOTE','INTERNSHIP',15000,25000,['Python','Flask','SQL','Git'],true,'Join a product engineering team and build real APIs, automations and internal tools.',['Python basics','SQL fundamentals','Git/GitHub'],['Remote','Certificate','PPO opportunity']],
['AI/ML Engineer','Microsoft','Hyderabad, India','HYBRID','FULL_TIME',1800000,3000000,['Python','Machine Learning','SQL','NLP'],false,'Build applied ML systems and intelligent experiences with measurable customer impact.',['Python and ML','Statistics fundamentals','Model evaluation'],['Global teams','Learning programs','Health cover']],
['Backend Developer','Flipkart','Bengaluru, India','ONSITE','FULL_TIME',1200000,2200000,['Java','Node.js','PostgreSQL','REST API'],false,'Design scalable backend services for high-volume commerce workflows.',['Backend development','Databases and APIs','System design basics'],['Employee discounts','Career growth','Insurance']],
['Data Analyst','Deloitte','Ahmedabad, India','HYBRID','FULL_TIME',700000,1200000,['SQL','Python','Power BI','Excel'],false,'Turn business data into insights and dashboards that support better decisions.',['SQL','Data visualization','Analytical thinking'],['Hybrid work','Mentoring','Certification support']],
['UI/UX Designer','Zomato','Gurugram, India','HYBRID','FULL_TIME',900000,1600000,['Figma','UX Research','Prototyping'],false,'Design simple, delightful experiences across consumer products.',['Figma','Portfolio','User-centered design'],['Creative culture','Flexible work','Learning budget']],
['DevOps Engineer','Infosys','Pune, India','ONSITE','FULL_TIME',900000,1500000,['AWS','Docker','CI/CD','Linux'],false,'Improve delivery pipelines, reliability and cloud infrastructure.',['Linux','Cloud basics','CI/CD'],['Training','Insurance','Global projects']]
];
function fresh():Store{
 const created=now();
 return {users:[{id:1,name:'CareerHub Recruiter',email:'recruiter@careerhub.demo',role:'RECRUITER',headline:'Talent Acquisition',location:'India',skills:['Recruiting','Hiring'],resumeUrl:null},{id:2,name:'Demo Candidate',email:'candidate@careerhub.demo',role:'CANDIDATE',headline:'Software Developer',location:'Ahmedabad, India',skills:['Java','Python','SQL','JavaScript','React'],resumeUrl:null},{id:3,name:'CareerHub Admin',email:'admin@careerhub.demo',role:'ADMIN',headline:'Platform Admin',location:'India',skills:[],resumeUrl:null}],jobs:seedJobs.map((j:any[],i)=>({id:i+1,title:j[0],company:j[1],location:j[2],workMode:j[3],employmentType:j[4],salaryMin:j[5],salaryMax:j[6],currency:'INR',skills:j[7],featured:j[8],description:j[9],requirements:j[10],benefits:j[11],status:'OPEN',recruiterId:1,createdAt:created,updatedAt:created,_count:{applications:0}})),applications:[],nextUserId:4,nextJobId:9,nextApplicationId:1};
}
function ensure(){if(!fs.existsSync(path.dirname(file)))fs.mkdirSync(path.dirname(file),{recursive:true});if(!fs.existsSync(file))fs.writeFileSync(file,JSON.stringify(fresh(),null,2));}
export function readStore():Store{ensure();try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{const s=fresh();writeStore(s);return s}}
export function writeStore(s:Store){ensure();fs.writeFileSync(file,JSON.stringify(s,null,2))}
export function listJobs(params:{q?:string;mode?:string;type?:string}={}){const s=readStore();const q=(params.q||'').toLowerCase();return s.jobs.filter(j=>j.status==='OPEN'&&(!params.mode||params.mode==='ALL'||j.workMode===params.mode)&&(!params.type||params.type==='ALL'||j.employmentType===params.type)&&(!q||[j.title,j.company,j.location,...j.skills].some(v=>v.toLowerCase().includes(q)))).sort((a,b)=>Number(b.featured)-Number(a.featured)||b.createdAt.localeCompare(a.createdAt));}
export function getJob(id:number){return readStore().jobs.find(j=>j.id===id)}
export function candidateWithApplications(){const s=readStore();const u=s.users.find(x=>x.id===2)!;return {...u,applications:s.applications.filter(a=>a.candidateId===2).sort((a,b)=>b.appliedAt.localeCompare(a.appliedAt)).map(a=>({...a,job:s.jobs.find(j=>j.id===a.jobId)}))}}
export function allApplications(){const s=readStore();return s.applications.sort((a,b)=>b.appliedAt.localeCompare(a.appliedAt)).map(a=>({...a,job:s.jobs.find(j=>j.id===a.jobId),candidate:s.users.find(u=>u.id===a.candidateId)}))}
export function createJob(b:any){const s=readStore();const t=now();const job:any={id:s.nextJobId++,title:String(b.title).trim(),company:String(b.company).trim(),location:String(b.location).trim(),workMode:b.workMode||'HYBRID',employmentType:b.employmentType||'FULL_TIME',salaryMin:b.salaryMin==null?null:Number(b.salaryMin),salaryMax:b.salaryMax==null?null:Number(b.salaryMax),currency:'INR',description:String(b.description).trim(),requirements:Array.isArray(b.requirements)?b.requirements:[],benefits:Array.isArray(b.benefits)?b.benefits:[],skills:Array.isArray(b.skills)?b.skills:[],featured:false,status:'OPEN',recruiterId:1,createdAt:t,updatedAt:t,_count:{applications:0}};s.jobs.push(job);writeStore(s);return job}
export function updateCandidate(b:any){const s=readStore();const u=s.users.find(x=>x.id===2)!;u.name=String(b.name||u.name).trim();u.headline=String(b.headline ?? u.headline ?? '').trim();u.location=String(b.location ?? u.location ?? '').trim();u.skills=Array.isArray(b.skills)?b.skills.map((x:any)=>String(x).trim()).filter(Boolean):u.skills;u.resumeUrl=b.resumeUrl?String(b.resumeUrl).trim():null;writeStore(s);return u}
export function applyToJob(jobId:number,b:any){const s=readStore();const job=s.jobs.find(j=>j.id===jobId);if(!job||job.status!=='OPEN')throw new Error('Job is no longer open');const candidate=s.users.find(u=>u.id===2)!;if(s.applications.some(a=>a.jobId===jobId&&a.candidateId===2)){const e=new Error('Already applied');(e as any).code='P2002';throw e}const overlap=job.skills.filter(sk=>candidate.skills.some(x=>x.toLowerCase()===sk.toLowerCase())).length;const score=Math.min(98,Math.round(overlap/Math.max(job.skills.length,1)*100)+35);const t=now();const a:Application={id:s.nextApplicationId++,jobId,candidateId:2,status:'APPLIED',coverLetter:b.coverLetter||'',resumeUrl:candidate.resumeUrl,matchScore:score,recruiterNote:null,appliedAt:t,updatedAt:t};s.applications.push(a);const j=s.jobs.find(x=>x.id===jobId);if(j)j._count={applications:s.applications.filter(x=>x.jobId===jobId).length};writeStore(s);return a}
export function patchApplication(b:any){const s=readStore();const a=s.applications.find(x=>x.id===Number(b.id));if(!a)throw new Error('Application not found');a.status=b.status||a.status;a.recruiterNote=b.recruiterNote??a.recruiterNote;a.updatedAt=now();writeStore(s);return a}
export function recruiterJobs(){const s=readStore();return s.jobs.filter(j=>j.recruiterId===1).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
